# Generated by Django 3.2.5 on 2021-07-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WriteToMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Имя клиента')),
                ('number', models.CharField(max_length=28, verbose_name='Номер телефона')),
                ('age', models.IntegerField(verbose_name='Возсраст')),
            ],
            options={
                'verbose_name': 'Заявки на прием',
                'verbose_name_plural': 'Заявка на прием',
            },
        ),
    ]
